/**
 * Generated workflow: ChatApp
 * Description: Real-time chat application with WebSocket support
 * Endpoints: GET /chat
 * Generated by Generative Backend Builder
 */

import { type Step, Workflow } from "@nanoservice-ts/helper";

// Real-time chat application with WebSocket support
const step: Step = Workflow({
  name: "chat-app",
  version: "0.1.0",
  description: "Real-time chat application with WebSocket support",
})
  .addTrigger("http", {
    method: "GET",
    path: "/chat",
    accept: "application/json",
  })
  .addStep({
    name: "render-chat",
    node: "chat-ui",
    type: "local",
    inputs: {
      title: "Real-time Chat",
      theme: "light"
    }
  });

export default step; 