/**
 * Generated workflow: create-movie
 * Description: Adds a new movie to the database
 * Endpoints: POST /api/movies
 * Generated by Generative Backend Builder
 * 
 * This is a placeholder file that will be replaced with a proper implementation.
 */

import { type Step, Workflow } from "@nanoservice-ts/helper";

// Define the workflow
const step: Step = Workflow({
  name: "create-movie",
  version: "0.1.0",
  description: "Adds a new movie to the database",
})
  .addTrigger("http", {
    method: "POST",
    path: "/api/movies",
    accept: "application/json",
  })
  .addStep({
    name: "add-movie-step",
    node: "add-movie",
    type: "module",
    inputs: {
      name: { $body: "name" },
      description: { $body: "description" },
      releaseYear: { $body: "releaseYear" }
    },
  });

export default step; 