/**
 * Example workflow
 * Description: A simple workflow that processes data
 * Endpoints: GET /api/example
 * Generated by Generative Backend Builder
 */

import { type Step, Workflow } from "@nanoservice-ts/helper";

// Define the workflow
const step: Step = Workflow({
  name: "example-workflow",
  version: "0.1.0",
  description: "A simple workflow that processes data",
})
  .addTrigger("http", {
    method: "GET",
    path: "/api/example",
    accept: "application/json",
  })
  .addStep({
    name: "process-data-step",
    node: "example-data-processor",
    type: "module",
    inputs: {
      data: {
        $value: {
          message: "Hello from the example workflow!",
          timestamp: new Date().toISOString()
        }
      }
    },
  });

export default step; 