/**
 * Generated workflow: list-movies
 * Description: Lists all movies in the database
 * Endpoints: GET /api/movies
 * Generated by Generative Backend Builder
 * 
 * This is a placeholder file that will be replaced with a proper implementation.
 */

import { type Step, Workflow } from "@nanoservice-ts/helper";

// Define the workflow
const step: Step = Workflow({
  name: "list-movies",
  version: "0.1.0",
  description: "Lists all movies in the database",
})
  .addTrigger("http", {
    method: "GET",
    path: "/api/movies",
    accept: "application/json",
  })
  .addStep({
    name: "fetch-movies-step",
    node: "fetch-movies",
    type: "module",
    inputs: {},
  });

export default step; 